/**
 * This data is borrowed somewhere from Web.
 * If you happens to be the owner, pls let me know so that I can acknowledge it here. Thanks!
 */
export default [
  "Aberfeldy Township",
  "Altona",
  "Arthurs Creek",
  "Arthurs Seat",
  "Ashwood",
  "Bacchus Marsh Werribee River",
  "Ballan",
  "Beaconsfield Upper",
  "Beenak",
  "Berwick",
  "Blackburn",
  "Blackburn North",
  "Blue Mountain",
  "Box Hill",
  "Braeside",
  "Braeside Park",
  "Broadmeadows",
  "Brooklyn",
  "Bulla",
  "Bulla North",
  "Bulleen",
  "Bundoora",
  "Burnley",
  "Burwood East",
  "Cambarville",
  "Cardinia",
  "Caulfield",
  "Caulfield North",
  "Cement Creek",
  "Christmas Hills",
  "Clarkefield",
  "Clarkefield",
  "Clayton",
  "Clearwater Aqueduct",
  "Coburg",
  "Coldstream",
  "Collingwood",
  "Craigieburn",
  "Craigieburn East",
  "Cranbourne",
  "Dandenong",
  "Dandenong South",
  "Dandenong West",
  "Darraweit",
  "Deer Park",
  "Devilbend Reservoir",
  "Diggers Rest",
  "Dixons Creek",
  "Doncaster",
  "Doncaster East",
  "Drouin West",
  "Durdidwarrah",
  "Eastern G.C. Doncaster",
  "Elsternwick",
  "Eltham",
  "Emerald",
  "Epping",
  "Essendon",
  "Fairfield",
  "Fawkner",
  "Fiskville",
  "Flemington",
  "Footscray",
  "Frankston North",
  "Frankston Pier",
  "Gardiner",
  "Glen Forbes South",
  "Glen Waverley",
  "Graceburn",
  "Graceburn Creek Aqueduct",
  "Greensborough",
  "Greenvale Reservoir",
  "Groom's Hill",
  "Hampton",
  "Hampton Park",
  "Hawthorn",
  "Headworks",
  "Healesville",
  "Heathmont", "Heidelberg",
  "Hurstbridge",
  "Iona",
  "Ivanhoe",
  "Kangaroo Ground",
  "Keilor",
  "Keilor North",
  "Kew",
  "Keysborough",
  "Kinglake",
  "Knox",
  "Konagaderra",
  "Kooweerup",
  "Lake Borrie",
  "Lancefield",
  "Lancefield North",
  "Launching Place",
  "Lilydale Lake",
  "Little River",
  "Loch",
  "Longwarry North",
  "Lower Plenty",
  "Lyndhurst",
  "Lysterfield",
  "Maribyrnong",
  "Maroondah Reservoir",
  "Melton Reservoir",
  "Melton Sth Toolern Creek",
  "Mentone",
  "Mernda",
  "Millgrove",
  "Mitcham",
  "Montrose",
  "Mooroolbark",
  "Mornington",
  "Mount Dandenong",
  "Mount Evelyn",
  "Mount View",
  "Mt Blackwood",
  "Mt Bullengarook",
  "Mt Donna Buang",
  "Mt Evelyn Stringybark Creek",
  "Mt Gregory",
  "Mt Hope",
  "Mt Horsfall",
  "Mt Juliet",
  "Mt Macedon",
  "Mt St Gwinear",
  "Mt St Leonard",
  "Mt Waverley",
  "Myrrhee",
  "Narre Warren North",
  "Nayook",
  "Neerim South",
  "Neerim-Elton Rd",
  "Neerim-Neerim Creek",
  "Neerim-Tarago East Branch",
  "Neerim-Tarago West Branch",
  "North Wharf",
  "Northcote",
  "Notting Hill",
  "Nutfield",
];
